issues:
  - issue: accepted
    articles:
    - title: "Multiple Factor Analysis for Contingency Tables in the FactoMineR Package"
      authors: "Belchin Kostov, Monica Becue-Bertaut and Francois Husson"
      url: "Kostov+Becue+Husson.pdf"

    - title: "Hypothesis Tests for Multivariate Linear Models Using the car Package"
      authors: "John Fox, Michael Friendly, and Sanford Weisberg"
      url: "Fox+Friendly+Weisberg.pdf"

    - title: "osmar: OpenStreetMap and R"
      authors: "Manuel J. A. Eugster and Thomas Schlesinger"
      url: "Eugster+Schlesinger.pdf"

    - title: "ftsa: An R Package for Analyzing Functional Time Series"
      authors: Han Lin Shang
      url: Shang.pdf

    - title: "Statistical Software from a Blind Person's Perspective"
      author: "A. Jonathan R. Godfrey"
      url: Godfrey.pdf

    - title: "QCA: A Package for Qualitative Comparative Analysis"
      authors: "Alrik Thiem and Adrian Dusa"
      url: Thiem+Dusa.pdf



