name: Publish new RJournal site from dev

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
     - name: Checkout dev branch
       uses: actions/checkout@v2
       with:
          ref: dev
          path: dev-branch

     - name: Checkout legacy content branch
       uses: actions/checkout@v2
       with:
          ref: legacy-content
          path: legacy

     - name: Merge legacy into dev _web
       run: |
          rsync -a legacy/ dev-branch/_web/
          
     - name: deploy
       uses: peaceiris/actions-gh-pages@v3
       with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dev-branch/_web
          publish_branch: deploy
