name: Build and deploy RJournal site

on:
  push:
    branches:
      - published
  workflow_dispatch:

jobs:
  jekyll:
    runs-on: ubuntu-20.04
    steps:
     - name: setup
       uses: actions/checkout@v2

     - name: setup ruby
       uses: ruby/setup-ruby@v1
       with:
          ruby-version: 2.6

     - name: build
       uses: limjh16/jekyll-action-ts@v2
       with:
          enable_cache: true

     - name: Checkout dev branch
       uses: actions/checkout@v2
       with:
          ref: dev
          path: dev-branch

     - name: Move dev content
       run: |
          rm -rf _site/dev
          mv dev-branch/_web _site/dev

     - name: deploy
       uses: peaceiris/actions-gh-pages@v3
       with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: deploy
