name: Build and deploy RJournal site

on:
  push:
    branches:
      - published
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
     - name: Checkout
       uses: actions/checkout@v2

     - uses: r-lib/actions/setup-r@v2
     - uses: r-lib/actions/setup-pandoc@v2
     
     - name: Install dependencies
       run: |
          export MAKEFLAGS=-j4
          sudo /bin/bash -c 'DEBCONF_NONINTERACTIVE_SEEN=true apt-get install -q -y libcurl4-openssl-dev'
          Rscript -e 'install.packages(c("rjtools","rmarkdown"),,c("https://rforge.net","https://cloud.R-project.org"))'

     - name: Render _web
       run: |
          rm -rf _web/ && Rscript -e 'rmarkdown::render_site()'

     - name: Checkout legacy content branch
       uses: actions/checkout@v2
       with:
          ref: legacy-content
          path: legacy

     - name: Merge legacy into dev _web
       run: |
          rsync -a legacy/ _web/

     - name: deploy
       uses: peaceiris/actions-gh-pages@v3
       with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_web
          publish_branch: deploy
