name: New RJournal site rendering test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
     - name: Checkout dev branch
       uses: actions/checkout@v2
       with:
          ref: dev
          path: dev-branch

     - uses: r-lib/actions/setup-r@v2
     - uses: r-lib/actions/setup-pandoc@v2
     
     - name: Install dependencies
       run: |
          export MAKEFLAGS=-j4
          sudo /bin/bash -c 'DEBCONF_NONINTERACTIVE_SEEN=true apt-get install -q -y libcurl4-openssl-dev'
          Rscript -e 'install.packages(c("rjtools","rmarkdown"),,c("https://rforge.net","https://cloud.R-project.org"))'

     - name: Re-render _web
       run: |
          rm -rf dev-branch/_web/ && (cd dev-branch && Rscript -e 'rmarkdown::render_site()')

     - name: deploy
       uses: peaceiris/actions-gh-pages@v3
       with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dev-branch/_web
          publish_branch: render-test
